from dataclasses import dataclass

@dataclass(frozen=True)
class const:
    SMALL_SPONSORS:str = """VP Clinical Operations OR VP of Clinical Development OR VP of Clinical Affairs OR Director Clinical Program OR Director of clinical trials OR Head of clinical data management OR Head of data management OR Clinical Operations Manager OR Chief Medical Officer OR Clinical Data Manager OR Clinical Project Manager OR Clinical Trial Manager OR Clinical and Scientific Affairs Manager OR Founder OR CEO OR CTO OR Clinical Project Coordinator OR Clinical Project Leader OR Clinical Consultant OR Clinical Investigator OR Research Project Manager OR Managing Director OR COO OR Medical Affairs Manager OR Clinical Investigator OR Clinical Research Specialist OR Clinical Study Leader Associate OR Clinical Study Coordinator OR Clinical Affairs Specialist OR Site Manager OR Clinical Study Leader Associate OR Clinical Research Specialist OR Quality Manager"""
    # Medium Sponsors
    MEDIUM_SPONSORS:str = """VP of eClinical Systems OR Director of Clinical Development & Operations OR Director of Clinical Research and Discovery OR VP Clinical Research & Evidence Generation OR Director of Data Management OR VP of Clinical Affairs OR VP of Clinical Operations OR Head of Clinical Development OR Head of Clinical Strategy OR Head of clinical services OR Head of research & clinical affairs OR Study Director OR eClincal Project Manager OR Clinical Project and Innovation Manager OR Senior Clinical Data Manager OR Clinical Studies Scientist & Project Manager OR Senior Clinical Project Manager OR Clinical Trial Manager OR Clinical and Scientific Affairs Manager OR Clinical and Medical Affairs Manager OR Clinical systems integration manager OR CMO OR CSO OR CTO OR Study Manager OR Clinical Strategy Manager OR Clinical systems analyst OR Clinical Project Coordinator OR Clinical Project Leader OR Clinical Operations Development Lead OR Clinical Consultant OR Clinical Investigator OR Clinical Scientist OR Research Project Manager OR Managing Director OR COO OR Founder OR CEO OR Clinical Investigator OR Clinical Research Specialist OR Clinical Study Leader Associate OR Clinical Study Coordinator OR Clinical Affairs Specialist OR Site Manager OR Clinical Study Leader Associate OR Clinical Research Specialist"""
    # Large Sponsors
    LARGE_SPONSORS:str = """VP of eClinical Systems OR Head of Patient Centric Solutions and Decentralized Clinical Trials OR VP, Clinical Digital and Decentralized Solutions OR Director of Clinical Vendor Manager OR Global Clinical Trial Program Head OR Director of Clinical Operations OR Head of clinical trial technology OR Head of Clinical Technology & Innovation OR Head of Global Clinical Operations OR VP of Clinical Affairs OR Director, Global Clinical Research & Medical Affairs OR Head of Clinical Development OR Global head of clinical data management OR VP Clinical Research & Evidence Generation OR Head of Clinical Technology & Innovation OR Senior Director of Clinical Strategy OR Vice President Clinical, Medical and Regulatory OR Clinical Development Center Director OR Global Clinical Project Management OR SVP, Head of Global Clinical Trial Operations OR Vice President of Clinical Development and Outcomes OR Senior Manager - Innovative Trials, Real World Data Science OR Director, Patient Recruitment & Retention RWE Clinical Trials OR Global Clinical Study Manager OR Associate Director, Clinical Trials OR Senior VP, Global Strategy & Development OR VP of Clinical Services OR Enterprise Clinical Trial Data Sharing Lead OR Head of Clinical Technology & Innovation OR Head of Data Operations OR Director of Patient Engagement & Recruitment OR Head Clinical Data Standards OR Director Innovative Data Analytics OR VP Clinical Portfolio Leader, Inflammation and Immunology OR Head of Rare Diseases Clinical Research OR VP Vaccine Clinical R&D OR Director, Clinical Pharmacology OR Director Clinical Site Operations & Head OR Head of Clinical trial diversity OR CMO OR CSO OR CTO OR COO OR Senior Database Developer, Clinical Data Sciences OR Head of Clinical trial diversity OR Clinical Process Optimization Manager OR Clinical Project and Innovation Manager OR Clinical Data Manager OR Clinical Compliance Manager OR Clinical Project Manager OR Clinical Trial Manager OR Clinical and Scientific Affairs Manager OR Clinical Vendor Analyst OR Clinical Data Integrity Analyst"""
    # Small CROs
    SMALL_CROS:str = """Head of Clinical Vendor Management OR VP of Clinical Development OR VP of Clinical Affairs OR Head of clinical data management OR Head of clinical project management OR Clinical Operations Manager OR Chief Medical Officer OR Clinical Data Manager OR Clinical Project Manager OR Clinical Trial Manager OR Clinical and Scientific Affairs Manager OR Director of Biostatistics OR Founder OR CEO OR CTO OR Clinical Project Coordinator OR Clinical Project Leader OR Clinical Consultant OR Clinical Investigator OR Research Project Manager OR Managing Director OR COO OR Clinical Implementation Specialist OR Clinical Investigator OR Clinical Research Specialist OR Clinical Study Leader Associate OR Clinical Study Coordinator OR Clinical Affairs Specialist OR Site Manager OR Clinical Study Leader Associate OR Clinical Research Specialist OR Quality Manager"""
    # Medium CROs
    MEDIUM_CROS:str = """Director of Clinical Solutions OR Director of eClinical Systems OR Director of Clinical Vendor Management OR Head of Clinical Technology Implementation OR VP of Clinical Operations OR VP of Clinical Affairs OR Director of Data Management OR Head of Clinical Development OR Global Head of Clinical Science OR Clinical Operations Manager OR Head of Clinical Strategy OR Head of clinical services OR Study Director OR Clinical Project and Innovation Manager OR Senior Clinical Data Manager OR Senior Clinical Project Manager OR Clinical Trial Manager OR Clinical and Scientific Affairs Manager OR Head of Digital Transformation OR Director of Biostatistics OR CMO OR CSO OR CTO OR Country Head of Clinical project operations OR Clinical Quality manager OR Clinical Project Lead OR Clinical Development Lead OR Clinical informatics specialist OR Clinical Operations Development Lead OR Clinical Consultant OR Clinical Investigator OR Clinical Scientist OR Research Project Manager OR Managing Director OR Founder OR CEO OR Medical affairs manager OR COO OR Clinical Investigator OR Clinical Research Specialist OR Clinical Study Leader Associate OR Clinical Study Coordinator OR Clinical Affairs Specialist OR Site Manager OR Clinical Study Leader Associate OR Clinical Research Specialist"""
    # Large CROs
    LARGE_CROS:str = """VP of eClinical Systems OR VP of eClinical solutions OR VP, Clinical Digital and Decentralized Solutions OR Director of Clinical Vendor Manager OR Director of Clinical Research Solutions Management OR Director of Clinical Operations OR Director, Innovative Analytics/Data Strategy/Clinical Trial Innovation OR Director of Strategic Clinical Procurement, Business & Vendor Partner OR Senior Vice President Clinical Development EMEA & APAC OR Senior Director, Clinical Program Management OR Director, Global Clinical Research & Medical Affairs OR Director of Clinical Vendor Manager OR Global Clinical Trial Program Head OR Director, Clinical Operations, Head of Biotech Clinical Operations Leaders OR Director of Clinical Operations OR Head of clinical trial technology OR Head of Clinical Technology & Innovation OR Head of Global Clinical Operations OR Head of Global Clinical Project Management OR VP of Clinical Affairs OR Global Clinical lead OR Senior Manager - Innovative Trials, Real World Data Science OR Director Clinical Strategy & Delivery OR Global Clinical Study Manager OR Executive Director - Clinical Data Operations (Clinical Informatics) OR Clinical Technology Implementation Manager OR Director of Clinical Data Sciences OR Senior clinical operations leader OR Director of RWE OR Director of Biostatistics OR Director of Patient Engagement & Recruitment OR Regional Operations Delivery, Clinical Operations OR Clinical Development Service Operations OR VP, Clinical Research Units, Early Development OR Director Clinical Transformation, Clinical Operations OR Director Clinical Site Operations & Head OR VP of Clinical Services OR Chief Medical Officer OR Head of Clinical Technology & Innovation OR Head of Data Operations OR Head of Clinical trial diversity OR Senior Database Developer, Clinical Data Sciences OR CMO OR CSO OR CTO OR COO OR Clinical Process Optimization Manager OR Head of Clinical Data standards OR Senior Clinical Data Manager OR Clinical Project and Innovation Manager OR Clinical Data Manager OR Clinical Compliance Manager OR Clinical Project Manager OR Clinical Trial Manager OR Clinical and Scientific Affairs Manager"""
    LINKEDIN_ENDPOINT:str = 'https://nubela.co/proxycurl/api/v2/linkedin'
    LINKEDIN_COMPANY_ENDPOINT:str = 'https://nubela.co/proxycurl/api/linkedin/company'
    LINKEDIN_ROLE_ENDPOINT:str = 'https://nubela.co/proxycurl/api/find/company/role/'
    NUBELA_EMPLOYEE_SEARCH:str = 'https://nubela.co//proxycurl/api/linkedin/company/employee/search/'
    NUBELA_CREDITS_ENDPOINT:str = 'https://nubela.co/proxycurl/api/credit-balance'
    ZOOM_INFO_CONTACT_ENDPOINT:str = "https://api.zoominfo.com/search/contact"
    ZOOM_INFO_ENRICH_ENDPOINT:str = 'https://api.zoominfo.com/enrich/contact'
    GOOGLE_SEARCH_ENPOINT:str = 'https://www.googleapis.com/customsearch/v1'
    OPENAI_API_VERSION:str = "2023-03-15-preview"
    OPENAI_API_TYPE:str = "azure"
    OPENAI_API_ENDPOINT:str = "https://cas-shs-uks-plg.openai.azure.com/"
    GOOGLE_SHEET_API_ENDPOINT:str = 'https://www.googleapis.com/auth/spreadsheets'
    GOOGLE_DRIVE_AUTH:str = 'https://www.googleapis.com/auth/drive'
    PROMPT_SYSTEM = '''
    You are the best BDR that has ever worked at Castor, or at any eClinical Company.
    For this task, you will refer to us as Castor. You are going to write a high quality, personalized, cold outbound message.
    You will be provided all relevant information about the business.
    Return only a valid JSON string, escape control characters like \\ and \\n for new lines.
    '''

    PROMPT_EMAIL = """
    You are going to write a high quality, personalized, cold outbound email for Castor, an eClinical company operating in life sciences.
    You will be provided with all the information about the company	  You will be provided with all the information about the company
    The number of Phase 1,2,3,4 trials they have conducted, The description of the company, their future pipeline.	  The number of Phase 1,2,3,4 trials they have conducted, The description of the company, their future pipeline.
    The goal is to give them a demo of our platform, either EDC, ePRO, eConsent, or all modules combined in a DCT workflow. Use one of the following value props: "Patient Centric", "Flexible", "Short Build timelines", "API first for integrations", "User-friendly", "Modular platform".	  The goal is to give them a demo of our platform, either EDC, ePRO, eConsent, or all modules combined in a DCT workflow. Use one of the following value props: "Patient Centric", "Flexible", "Short Build timelines", "API first for integrations", "User-friendly", "Modular platform".
    The focus is on understanding their pain points and demonstrating how Castor best help them run their clinical trials company's size, therapeutic area and pipeline.	  The focus is on understanding their pain points and demonstrating how Castor best help them run their clinical trials company's size, therapeutic area and pipeline.
    The messaging should be tailored to the specific personas and company profiles, highlighting the value and benefits of Castor’s offerings.	  The messaging should be tailored to the specific personas and company profiles, highlighting the value and benefits of Castor’s offerings.
    Always link castors value propositions back to the goals and objectives for the prospect and target company.	  Always link castors value propositions back to the goals and objectives for the prospect and target company.
    DO NOT MENTION funding rounds unless they are in last 3 months, and DON'T dwell on it.	  DO NOT MENTION funding rounds unless they are in last 3 months, and DON'T dwell on it.
    DO NOT EXPLAIN THE COMPANY BACK TO THEM. Never EXPLAIN what they do, just show we understand what we do.	  DO NOT EXPLAIN THE COMPANY BACK TO THEM. Never EXPLAIN what they do, just show we understand what we do.
    Optimize the email for open and response rates by levegaring the contact information, including their own linkedin summary, and the company's pipeline.	  Optimize the email for open and response rates by levegaring the contact information, including their own linkedin summary, and the company's pipeline.
    The email must NOT be salesy, but sound HELPFUL and TO THE POINT.	  The email must NOT be salesy, but sound HELPFUL and TO THE POINT.
    Don't mention "paint points" and other generic sales talk, focus on 1 likely problem they might have.	  Don't mention "paint points" and other generic sales talk, focus on 1 likely problem they might have.
    The INTRO must be short and snappy, get straight to the point	  The INTRO must be short and snappy, get straight to the point
    The email must ALWAYS be 5 paragrahps long, the first one is "Hello {{Recipient.FirstName}}".	  THe email must ALWAYS be 5 paragrahps long, the first one is "Hello {{Recipient.FirstName}}".
    There should be no end, No closing, NO SIGNATURE, No greetings, only subject and 3 email body paragraphs	  There should be no end, No closing, NO SIGNATURE, No greetings, only subject and 3 email body paragraphs
    Salutation should always be "Hello {{Recipient.FirstName}}," using Pardot template tags, don't but in the action email.	  Salutation should always be "Hello {{Recipient.FirstName}}," using Pardot template tags, don't but in the action email.
    You MUST make the Subject include some custom, for example a future trial or something mentioning therapeutic areas. 	  You MUST make the Subject include some custom, for example a future trial or something mentioning therapeutic areas. 
    In the third paragraph you must never write the phrase "looking forward to", instead leave a open ended question like "would you be open to a demo" or "would you be open to a conversation", etc. It 	  In the 3rd body paragraph you must never write the phrase "looking forward to", instead leave a open ended question like "would you be open to a demo" or "would you be open to a conversation", etc. It 
    is important that you leave the closing statment of paragraph 3 open ended depending on the context of the email and do not only use the terms mentioned above, try to come up with witty open ended closing remarks	  is important that you leave the closing statment of 3rd body paragraph open ended depending on the context of the email and do not only use the terms mentioned above, try to come up with witty open ended closing remarks
    in paragraph 3. 	  in the 3rd body paragraph. 
    Critical Note: 
        -No paragraph can ever be empty.  
    """