# Generated by Django 5.0.4 on 2024-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach_app', '0002_runningjob_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningjob',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runningjob',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
